INSERT INTO tb_category (name) VALUES ('Módulo Vidro');
INSERT INTO tb_category (name) VALUES ('Substituir Original');
INSERT INTO tb_category (name) VALUES ('Auto Down');
INSERT INTO tb_category (name) VALUES ('Alarme');
INSERT INTO tb_category (name) VALUES ('Interface Volante');
INSERT INTO tb_category (name) VALUES ('Trava Elétrica');
INSERT INTO tb_category (name) VALUES ('Travamento por Velocidade');
INSERT INTO tb_category (name) VALUES ('Subst. Trava Original');
INSERT INTO tb_category (name) VALUES ('Central Engate');
INSERT INTO tb_category (name) VALUES ('Teto Solar');
INSERT INTO tb_category (name) VALUES ('Retrovisor');
INSERT INTO tb_category (name) VALUES ('Desliga Rádio');


INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW52', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('One', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW52', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');


INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 1);


