INSERT INTO tb_category (name) VALUES ('Módulo Vidro');
INSERT INTO tb_category (name) VALUES ('Substituir Original');
INSERT INTO tb_category (name) VALUES ('Auto Down');
INSERT INTO tb_category (name) VALUES ('Alarme');
INSERT INTO tb_category (name) VALUES ('Interface Volante');
INSERT INTO tb_category (name) VALUES ('Trava Elétrica');
INSERT INTO tb_category (name) VALUES ('Travamento por Velocidade');
INSERT INTO tb_category (name) VALUES ('Subst. Trava Original');
INSERT INTO tb_category (name) VALUES ('Central Engate');
INSERT INTO tb_category (name) VALUES ('Teto Solar');
INSERT INTO tb_category (name) VALUES ('Retrovisor');
INSERT INTO tb_category (name) VALUES ('Desliga Rádio');


INSERT INTO tb_manufacturer (name,url_Image) VALUES ('CHEVROLET','Http://wwww.image.com');
INSERT INTO tb_manufacturer (name,url_Image) VALUES ('FIAT','Http://wwww.image.com');
INSERT INTO tb_manufacturer (name,url_Image) VALUES ('FORD','Http://wwww.image.com');
INSERT INTO tb_manufacturer (name,url_Image) VALUES ('VOLKSWAGEN','Http://wwww.image.com');
INSERT INTO tb_manufacturer (name,url_Image) VALUES ('RENAULT','Http://wwww.image.com');
INSERT INTO tb_manufacturer (name,url_Image) VALUES ('HONDA','Http://wwww.image.com');
INSERT INTO tb_manufacturer (name,url_Image) VALUES ('TOYOTA','Http://wwww.image.com');
INSERT INTO tb_manufacturer (name,url_Image) VALUES ('CITROEN','Http://wwww.image.com');
INSERT INTO tb_manufacturer (name,url_Image) VALUES ('MERCEDES','Http://wwww.image.com');
INSERT INTO tb_manufacturer (name,url_Image) VALUES ('HYUNDAI','Http://wwww.image.com');



INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW52', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('One', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW52', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('LC Reboque Easy', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');
INSERT INTO tb_product (name,model,warranty,description,complement,url_Manual,url_Video,url_Wiring_Diagram, url_Img_Prod) VALUES ('AW32', 'AA.29.0016', 2, 'Efetuar a instalação de levantamento no botão do vidro','Seguir esquema de levantamanto dos vidros do manual INFINITY','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AA.29.0025.PNG', 'https://www.youtube.com/watch?v=Zovr9rpeEOE&t=89s','http://www.softautomotiva.com.br/esquemas/GM/ONIX_JOY_PRISMA_JOY_COBALT_PP_AW32', 'http://www.softautomotiva.com.br/images/cve_aw52.jpg?crc=3783142226');


INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 1);
INSERT INTO tb_car (name,year) VALUES ('Prisma','2010');
INSERT INTO tb_car (name,year) VALUES ('Palio','2002');
INSERT INTO tb_car (name,year) VALUES ('Focus','2020');
INSERT INTO tb_car (name,year) VALUES ('Voyage','2014');
INSERT INTO tb_car (name,year) VALUES ('C3 Air Cross','2010');
INSERT INTO tb_car (name,year) VALUES ('Sandeiro','2007');
INSERT INTO tb_car (name,year) VALUES ('Honda Civic','2000');
INSERT INTO tb_car (name,year) VALUES ('Corolla','2014');
INSERT INTO tb_car (name,year) VALUES ('Classe A','2019');
INSERT INTO tb_car (name,year) VALUES ('Tucson','2018');
INSERT INTO tb_car (name,year) VALUES ('Creta','2020');
INSERT INTO tb_car (name,year) VALUES ('Onix','2015');
INSERT INTO tb_car (name,year) VALUES ('Mobi','2019');
INSERT INTO tb_car (name,year) VALUES ('Fiesta','2000');
INSERT INTO tb_car (name,year) VALUES ('Golf','2013');
INSERT INTO tb_car (name,year) VALUES ('Gol G6','2011');
INSERT INTO tb_car (name,year) VALUES ('Megane','2010');
INSERT INTO tb_car (name,year) VALUES ('Honda City','2020');
INSERT INTO tb_car (name,year) VALUES ('C4 Pallace','2010');
INSERT INTO tb_car (name,year) VALUES ('Classe C','2021');
INSERT INTO tb_car (name,year) VALUES ('Classe GLC','2021');
INSERT INTO tb_car (name,year) VALUES ('Nivus','2021');
INSERT INTO tb_car (name,year) VALUES ('Captur','2014');
INSERT INTO tb_car (name,year) VALUES ('Duster','2016');
INSERT INTO tb_car (name,year) VALUES ('Logan','2007');
INSERT INTO tb_car (name,year) VALUES ('Doblo','1998');
INSERT INTO tb_car (name,year) VALUES ('Siena','1997');
INSERT INTO tb_car (name,year) VALUES ('Cronos','2020');
INSERT INTO tb_car (name,year) VALUES ('Fit Uno','1994');
INSERT INTO tb_car (name,year) VALUES ('Pollo','2011');
INSERT INTO tb_car (name,year) VALUES ('PRISMA','2011');
INSERT INTO tb_car (name,year) VALUES ('PRISMA','2012');
INSERT INTO tb_car (name,year) VALUES ('PRISMA','2013');
INSERT INTO tb_car (name,year) VALUES ('PRISMA','2014');
INSERT INTO tb_car (name,year) VALUES ('PRISMA','2015');
INSERT INTO tb_car (name,year) VALUES ('PRISMA','2016');
INSERT INTO tb_car (name,year) VALUES ('PRISMA','2017');
INSERT INTO tb_car (name,year) VALUES ('PRISMA','2018');
INSERT INTO tb_car (name,year) VALUES ('Gol G6','2019');
INSERT INTO tb_car (name,year) VALUES ('PRISMA','2020');
INSERT INTO tb_car (name,year) VALUES ('Fiat Uno','2013');
INSERT INTO tb_car (name,year) VALUES ('Fiat Uno','2014');
INSERT INTO tb_car (name,year) VALUES ('Fiat Uno','2015');
INSERT INTO tb_car (name,year) VALUES ('Fiat Uno','2016');


INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(1,1);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(2,2);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(3,3);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(4,4);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(5,5);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(6,6);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(7,7);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(8,8);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(9,9);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(10,10);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(11,1);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(12,2);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(13,3);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(14,4);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(15,5);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(16,6);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(17,7);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(18,8);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(19,9);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(20,10);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(21,1);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(22,1);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(23,1);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(24,3);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(25,4);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(26,5);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(27,6);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(28,7);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(29,8);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(30,9);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(31,10);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(32,1);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(33,1);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(34,5);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(35,4);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(36,4);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(37,2);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(38,9);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(39,1);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(40,3);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(41,5);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(42,3);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(43,6);
INSERT INTO tb_car_manufacturer(car_id,manufacturer_id) VALUES(44,7);

